name: bevvy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.2
  introduction_screen: ^3.1.14
  google_fonts: 6.2.1
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.15.4
  dio: ^5.4.3+1
  flutter_card_swiper: ^7.0.1
  lottie: ^3.1.0
  firebase_crashlytics: ^3.4.15
  firebase_analytics: ^10.8.5
  archive: ^3.6.1  # 호환성 유지를 위해 버전 낮춤
  async: ^2.11.0  # 호환성 유지를 위해 버전 낮춤
  boolean_selector: ^2.1.1  # 호환성 유지를 위해 버전 낮춤
  characters: ^1.3.0  # 호환성 유지를 위해 버전 낮춤
  clock: ^1.1.1  # 호환성 유지를 위해 버전 낮춤
  collection: ^1.19.0  # 호환성 유지를 위해 버전 낮춤
  dots_indicator: ^2.1.2  # 호환성 유지를 위해 버전 낮춤
  fake_async: ^1.3.1  # 호환성 유지를 위해 버전 낮춤
  leak_tracker: ^10.0.7  # 호환성 유지를 위해 버전 낮춤
  leak_tracker_flutter_testing: ^3.0.8  # 호환성 유지를 위해 버전 낮춤
  matcher: ^0.12.16+1  # 호환성 유지를 위해 버전 낮춤
  material_color_utilities: ^0.11.1  # 호환성 유지를 위해 버전 낮춤
  meta: ^1.15.0  # 호환성 유지를 위해 버전 낮춤
  path: ^1.9.0  # 호환성 유지를 위해 버전 낮춤
  source_span: ^1.10.0  # 호환성 유지를 위해 버전 낮춤
  stack_trace: ^1.12.0  # 호환성 유지를 위해 버전 낮춤
  stream_channel: ^2.1.2  # 호환성 유지를 위해 버전 낮춤
  string_scanner: ^1.3.0  # 호환성 유지를 위해 버전 낮춤
  term_glyph: ^1.2.1  # flutter_test와 호환
  test_api: ^0.7.3  # flutter_test와 호환
  vm_service: 14.3.0  # flutter_test와 호환

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
